### ISSUE TITLE
Failure in dojo.js

### ISSUE THREAD

**Issue by ericlentz** [theintern/intern-tutorial#19]
On Linux Mint 17.1 (Build on Ubuntu Trusty (14.04)), followed the tutorial and get this:

```
FATAL ERROR
Error: Failed to load module app/hello from /home/edl/tmp/pm/intern-tutorial/hello.js (parent: tests/hello)
  at <../../../../../usr/local/lib/node_modules/intern/node_modules/dojo/dojo.js:757:12>
  at <fs.js:207:20>
  at Object.oncomplete  <fs.js:107:15>
```

Maybe it is because of dojo 2.0.0?

Here are the versions from npm install intern --save-dev:

```
intern@2.2.2 node_modules/intern
├── diff@1.1.0
├── charm@0.2.0
├── source-map@0.1.33 (amdefine@0.1.0)
├── leadfoot@1.2.1 (dojo@2.0.0-alpha4)
├── chai@1.9.1 (assertion-error@1.0.0, deep-eql@0.1.3)
├── digdug@1.2.1 (dojo@2.0.0-alpha4, decompress@0.2.3)
├── istanbul@0.2.16 (which@1.0.9, abbrev@1.0.5, nopt@3.0.1, wordwrap@0.0.2, async@0.9.0, resolve@0.7.4, mkdirp@0.5.0, fileset@0.1.5, esprima@1.2.5, escodegen@1.3.3, handlebars@1.3.0, js-yaml@3.2.7)
└── dojo@2.0.0-dev
```

**Comment by csnover** [comment]
You’ve skipped part of step 2. :)

**Comment by ericlentz** [comment]
Yes,
  location: '.'
didn't get changed to 
  location: 'app'

I changed name: 'myPackage' to name: 'app', but didn't see the location part. I see that now.

Thanks!
