### ISSUE TITLE
intern-client error: missing required argument "config"

### ISSUE THREAD

**Issue by sandrina-p** [theintern/intern-tutorial#32]
I'm following your [inter-tutorial](https://github.com/theintern/intern-tutorial). 

I did:

`./node_modules/.bin/intern-client config=tests/intern`

output: `0/0 tests failed`

`intern-client`

Output: `command not found`

`npm install -g intern`

`intern-client`

Output:

```
Error: Missing required argument "config"
  at PreExecutor.getConfig  <../../../../usr/local/lib/node_modules/intern/lib/executors/PreExecutor.js:137:11>
  at getConfig  <../../../../usr/local/lib/node_modules/intern/lib/executors/PreExecutor.js:410:17>
  at <../../../../usr/local/lib/node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at run  <../../../../usr/local/lib/node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <../../../../usr/local/lib/node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at process._tickCallback  <node.js:349:13>
```

What I am missing here?

Thanks

**Comment by sandrina-p** [comment]
Never mind, I had to write `intern-client config=tests/intern` it was missing `config=tests/intern`.

**Comment by dylans** [comment]
Glad you got things working @sandrina-p
